name: Test Docker Image

on:
    push:
      paths:
        - Dockerfile
        - root/**
      branches-ignore:
        - main
    pull_request:

jobs:
    build:
        name: Test Image Builds
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build image
              uses: docker/build-push-action@v5 
              with:
                context: .
                push: false
                tags: ${{ github.ref_name }}
                cache-to: type=gha, mode=max, scope=${{ github.ref_name }}
                cache-from: |
                    type=gha
                    type=gha, scope=${{ github.ref_name }}